CREATE OR REPLACE TABLE DBT_ANALYTICS.DBT.MODEL_RECOMMENDATIONS (
    MODEL_NAME STRING,
    QUERY_TEXT STRING,
    RUN_TIME NUMBER,
    MATERIALIZATION STRING,
    ROWS_AFFECTED STRING,
    RECOMMENDATION STRING,
    RECOMMENDATION_GIST STRING
);
