name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install schemachange snowflake-connector-python

      - name: Configure Snowflake connection
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: github_workflow_user
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          # Decode and set the private key
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
        run: |
          echo "Step 1: Decoding and exporting the private key"
          echo $SNOWFLAKE_PRIVATE_KEY | base64 --decode > rsa_key.p8
          
          # Export environment variables for Snowflake Python connector
          export SNOWFLAKE_PRIVATE_KEY_PATH=$(pwd)/rsa_key.p8

      - name: Run schemachange with key pair authentication
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: github_workflow_user
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SNOWFLAKE_PRIVATE_KEY_PATH: ${{ env.SNOWFLAKE_PRIVATE_KEY_PATH }}
        run: |
          echo "Step 2: Running schemachange"
          schemachange deploy \
            -f $GITHUB_WORKSPACE/migrations \
            -a $SF_ACCOUNT \
            -u $SF_USERNAME \
            -r $SF_ROLE \
            -w $SF_WAREHOUSE \
            -d $SF_DATABASE \
            -s "" \  # Specify schema if needed, else leave as empty string
            -c "$SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table

      - name: Clean up
        run: |
          rm rsa_key.p8
