name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install schemachange snowflake-connector-python

      - name: Configure Snowflake connection
        env:
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
        run: |
          echo "Decoding and exporting the private key"
          echo $SF_PRIVATE_KEY | base64 --decode > private_key.pem
          echo "SNOWFLAKE_PRIVATE_KEY_PATH=private_key.pem" >> $GITHUB_ENV
          # If your private key is encrypted, provide the passphrase as well
          # echo "SNOWFLAKE_PRIVATE_KEY_PASSPHRASE=${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "SF_PRIVATE_KEY_PATH: $SNOWFLAKE_PRIVATE_KEY_PATH"
          echo "SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: $SNOWFLAKE_PRIVATE_KEY_PASSPHRASE"
          echo "SF_ROLE: ${{ secrets.SF_ROLE }}"

      - name: Run schemachange with key pair authentication
        env:
          SF_PRIVATE_KEY_PATH: ${{ env.SF_PRIVATE_KEY_PATH }}
          SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }} # Comment out if not used
        run: |
          echo "Step 2: Running schemachange"
          schemachange deploy \
            -f $GITHUB_WORKSPACE/migrations \
            -a ${{ secrets.SF_ACCOUNT }} \
            -u ${{ secrets.SF_USERNAME }} \
            -r ${{ secrets.SF_ROLE }} \
            -w ${{ secrets.SF_WAREHOUSE }} \
            -d ${{ secrets.SF_DATABASE }} \
            -s ${{ secrets.SF_SCHEMA }} \
            -c ${{ secrets.SF_DATABASE }}.SCHEMACHANGE.CHANGE_HISTORY \
            --create-change-history-table

      - name: Clean up
        run: |
          rm private_key.pem
